### ISSUE TITLE
Warning System Problem

### ISSUE THREAD

**Issue by good777LUCKY** [llama-development/BanSystemNK#4]
I love warning system! Thank you for adding this feature! (#1) But I have a problem. I can't warn the player who is not online. When I know that the player did something wrong, I can't warn the player if the player just leave the game. Can you add feature that can warn the offline player?

**Comment by Mundschutziii** [comment]
Hi, sure, I'll be adding that in the next few days.

**Comment by good777LUCKY** [comment]
Thank you!

**Comment by Mundschutziii** [comment]
A new version is now available on NukkitX.
