### ISSUE TITLE
[Looping Critical Error!] Something is conflicting with plugins

### ISSUE THREAD

**Issue by good777LUCKY** [llama-development/BanSystemNK#5]
I have a critical looping error when I use this plugin, Luckperm, and ZChat. What plugin make this endless error?

Log:
http://nukkitx.eu/uxibumufez.css

**Comment by PocketMiner82** [comment]
I think the error is caused by ZChat.

**Comment by good777LUCKY** [comment]
ok, i will ask ZChat developer, too.

**Comment by Mundschutziii** [comment]
Thanks for your report.
A fix will be published in the next few days. I will probably have to put a small cool down when a player joins the game to prevent this mistake from happening again.

**Comment by good777LUCKY** [comment]
thank you!

**Comment by Mundschutziii** [comment]
The error should be fixed now.
https://nukkitx.com/resources/bansystem.332/updates#resource-update-1115
