### ISSUE TITLE
Add Inventory UI

### ISSUE THREAD

**Issue by DeveloperNeb101** [llama-development/BanSystemNK#8]
Add a choice of having an inventory ui like in java instead of a form. I think this will appeal to alot of people and really rocket this plugin

**Comment by ProxmaDev** [comment]
I don't think that's a good Idea. BanSystem should be usable for mobile too.

**Comment by DeveloperNeb101** [comment]
Make it an option, form or invent ui

**Comment by ProxmaDev** [comment]
Just use forms, lol. It's the same, just better and easier to use.
You can find the UI extension here: https://nukkitx.com/resources/bansystem-ui-addon.468/

There is no reason to add a ChestUI in my opinion.

**Comment by DeveloperNeb101** [comment]
ChestUI is much cleaner and better for pc players which is why it should be an option. So u dont have to scroll through a long form u can clikc a diamond for example to ban for xray

**Comment by ProxmaDev** [comment]
You can use forms on your PC too. With a ChestUI you need to hover over every item to see which Ban Reason it has. That takes MUCH longer than scrolling a second.
